## o try tambem nao trata identação pois continua sendo um erro de sintax . 


# try : 
#     for loop in range (1, 10) : 
#     print (loop)
    
# Exception IndentationError :
#     print ("Arruma isso :D ")